
CREATE  DATABASE IF NOT EXISTS test1;
CREATE  DATABASE test2;
CREATE  DATABASE test3;
CREATE USER 'test'@'%' IDENTIFIED BY 'test';
GRANT ALL ON test1.* TO 'test'@'%';
GRANT ALL ON test2.* TO 'test'@'%';
GRANT ALL ON test3.* TO 'test'@'%';
FLUSH PRIVILEGES ;